apiVersion: v1
kind: ConfigMap
metadata:
  name: gomirai-config
  namespace: gomirai
data:
  # Infrastructure Hosts (Sá» dá»¥ng tÃªn Service trong K8s)
  SPRING_CLOUD_CONSUL_HOST: "consul-service"
  SPRING_CLOUD_CONSUL_PORT: "8500"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb-service.gomirai.svc.cluster.local:27017/gomirai?replicaSet=rs0"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:29092"
  
  # Logging & Discovery
  SPRING_CACHE_TYPE: "redis"
  LOGGING_LEVEL_ROOT: "INFO"
  SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: "true"
  SPRING_CLOUD_CONSUL_CONFIG_ENABLED: "true"
  
  # Business Config
  CORS_ALLOWED_ORIGINS: "http://34.84.137.183,http://localhost:5173"
